# Generated by Django 5.0 on 2023-12-11 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(blank=True, max_length=50, null=True)),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='image')),
                ('question_description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('category', models.CharField(blank=True, choices=[('Dresses', 'Dresses'), ('Mens', "Men's Dresses"), ('Women', "Women's Dresses"), ('Baby', "Baby's Dresses"), ('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Sweater', 'Sweater'), ('Sleepwear', 'Sleepwear'), ('Blazers', 'Blazers'), ('Jackets', 'Jackets'), ('Shoes', 'Shoes'), ('Accerssories', 'Accerssories'), ('Bags', 'Bags')], max_length=250, null=True)),
                ('brand', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='image')),
                ('sizes', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=250, null=True)),
                ('win_collection', models.BooleanField(blank=True, default=False, null=True)),
                ('spring_collection', models.BooleanField(blank=True, default=False, null=True)),
                ('trandy_products', models.BooleanField(blank=True, default=False, null=True)),
                ('just_arrived', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('province', models.CharField(choices=[('', 'Select division'), ('Dhaka', 'Dhaka'), ('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Barishal', 'Barishal'), ('Chattogram', 'Chattogram'), ('Mymensingh ', 'Mymensingh '), ('sylhet', 'sylhet')], max_length=250)),
                ('city', models.CharField(choices=[('', 'Select District'), ('Dhaka', 'Dhaka'), ('Bogra', 'Bogra'), ('Sirajganj', 'Sirajganj'), ('Brahmanbaria', 'Brahmanbaria'), ('Tangail', 'Tangail'), ('Pabna', 'Pabna'), ('Noakhali', 'Noakhali'), ('Mymensingh', 'Mymensingh'), ('Rajshahi', 'Rajshahi'), ('Gazipur', 'Gazipur'), ('Barisal', 'Barisal'), ('Jessore', 'Jessore'), ('Satkhira', 'Satkhira'), ('Narayanganj', 'Narayanganj'), ('Bandarban', 'Bandarban'), ('Natore', 'Natore'), ('Faridpur', 'Faridpur'), ('Khulna', 'Khulna'), ('Rangpur', 'Rangpur'), ('Comilla', 'Comilla'), ('Dinajpur', 'Dinajpur'), ('Munshiganj', 'Munshiganj'), ('Feni', 'Feni'), ('Narsingdi', 'Narsingdi'), ('Rangamati ', 'Rangamati '), ('Noakhali  ', 'Noakhali'), ('Panchagarh', 'Panchagarh'), ('Bhola', 'Bhola'), ('Chandpur', 'Chandpur'), ('Habiganj', 'Habiganj'), ('Lakshmipur', 'Lakshmipur'), ('Barguna', 'Barguna'), ('Jhalokati', 'Jhalokati'), ('Pirojpur', 'Pirojpur'), ('Jhenaidah', 'Jhenaidah'), ('Narail', 'Narail'), ('Magura', 'Magura'), ('Lalmonirhat', 'Lalmonirhat'), ('Kurigram', 'Kurigram'), ('Gaibandha', 'Gaibandha'), ('Thakurgaon', 'Thakurgaon'), ('Sherpur', 'Sherpur'), ('Gopalganj', 'Gopalganj'), ("Cox's Bazar", "Cox's Bazar"), ('Sunamganj', 'Sunamganj'), ('Naogaon', 'Naogaon'), ('Natore', 'Natore'), ('Joypurhat', 'Joypurhat')], max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('area', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_topic', models.CharField(choices=[('Customer Service', 'Customer Service'), ('Online Orders', 'Online Orders'), ('My Rewards', 'My Rewards'), ('Club Taaga', 'Club Taaga'), ('Corporate Enquiry', 'Corporate Enquiry'), ('Partership opportunities', 'Partership opportunities'), ('General', 'General')], max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('messages', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlacedFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(default='Unknown', max_length=250)),
                ('month', models.CharField(default='01', max_length=2)),
                ('year', models.CharField(default='2023', max_length=4)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('cvv_code', models.CharField(default='00', max_length=4)),
                ('billing_address', models.CharField(default='N/A', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('one the way', 'on the way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], max_length=250)),
                ('addressbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce_app.addressbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proudct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_rating', models.PositiveSmallIntegerField(null=True, unique=True)),
                ('your_review', models.TextField()),
                ('your_name', models.CharField(max_length=250)),
                ('your_email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
