# Generated by Django 5.0 on 2023-12-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
