# Generated by Django 5.0 on 2023-12-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0002_alter_faq_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplacedformmodel',
            name='month',
            field=models.CharField(choices=[('(01) Jan', '(01) Jan'), ('(02) Feb', '(02) Feb'), ('(03) Mar', '(03) Mar'), ('(04) Apr', '(04) Apr'), ('(05) May', '(05) May'), ('(06) Jun', '(06) Jun'), ('(07) Jul', '(07) Jul'), ('(08) Aug', '(08) Aug'), ('(09) Sep', '(09) Sep'), ('(10) Oct', '(10) Oct'), ('(11) Nov', '(11) Nov'), ('(12) Dec', '(12) Dec')], default='01', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderplacedformmodel',
            name='year',
            field=models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044'), ('2045', '2045'), ('2046', '2046'), ('2047', '2047'), ('2048', '2048'), ('2049', '2049'), ('2050', '2050'), ('2051', '2051'), ('2052', '2052')], default='2023', max_length=15),
        ),
    ]
