# Generated by Django 5.0 on 2023-12-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0003_alter_orderplacedformmodel_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fashionable_dress',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reasonable_price',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
