# Generated by Django 5.0 on 2023-12-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0004_product_fashionable_dress_product_reasonable_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='question_img',
        ),
    ]
