# Generated by Django 5.0 on 2023-12-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0005_remove_faq_question_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplacement',
            old_name='proudct',
            new_name='product',
        ),
    ]
