# Generated by Django 5.2.5 on 2025-10-20 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0006_rename_proudct_orderplacement_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplacement',
            name='payment_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce_app.orderplacedformmodel'),
        ),
        migrations.AlterField(
            model_name='orderplacement',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('one the way', 'on the way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=250),
        ),
    ]
